import { build } from 'esbuild';
import { readFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const outfile = 'shared/runtime.generated.js';
const check = process.argv.includes('--check');
const expectedInputs = [
  'lib/bloomberg-heuristics.mjs',
  'lib/china-commerce-heuristics.mjs',
  'lib/constants.mjs',
  'lib/cookie-heuristics.mjs',
  'lib/host.mjs',
  'lib/overlay-heuristics.mjs',
  'lib/safari.mjs',
  'lib/settings.mjs',
  'lib/substack-detect.mjs',
  'lib/substack-heuristics.mjs',
  'lib/text.mjs',
  'lib/tos-heuristics.mjs'
];

const result = await build({
  absWorkingDir: root,
  entryPoints: ['src/classic-runtime.mjs'],
  outfile,
  bundle: true,
  format: 'iife',
  platform: 'browser',
  target: ['chrome109', 'firefox115', 'safari16.4'],
  charset: 'ascii',
  legalComments: 'none',
  minify: false,
  sourcemap: false,
  write: !check,
  metafile: true,
  banner: { js: '/* Generated by scripts/build-runtime.mjs. Do not edit. */' }
});

const inputs = Object.keys(result.metafile.inputs);
for (const expected of expectedInputs) {
  if (!inputs.some((input) => input === expected || input.endsWith(`/${expected}`))) {
    throw new Error(`runtime bundle is missing canonical module: ${expected}`);
  }
}

if (check) {
  const expected = await readFile(join(root, outfile), 'utf8');
  const generated = result.outputFiles?.[0]?.text;
  if (generated !== expected)
    throw new Error('shared/runtime.generated.js is stale; run npm run build:runtime');
  console.log('classic runtime is current');
} else {
  console.log('classic runtime generated');
}
